name: "Extract Jira Key"
description: "Extract Jira issue key from GitHub issue labels"

inputs:
  github-token:
    description: "GitHub token"
    required: true

outputs:
  jira_key:
    description: "Extracted Jira issue key"
    value: ${{ steps.extract.outputs.jira_key }}

runs:
  using: "composite"
  steps:
    - name: Extract Jira Key
      id: extract
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const issue_number = context.payload.issue.number;
          const labels = context.payload.issue.labels.map(label => label.name);
          console.log(`Labels for issue #${issue_number}: ${labels.join(", ")}`);

          let jiraKey = null;
          for (const label of labels) {
            const match = label.match(/^([A-Z]{2,})-(\d+)$/);
            if (match) {
              jiraKey = match[0];
              console.log(`Found Jira key in label: ${jiraKey}`);
              break;
            }
          }

          if (!jiraKey) {
            console.log("No Jira key found in labels");
            core.setOutput("jira_key", "");
          } else {
            core.setOutput("jira_key", jiraKey);
          }
