services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.fe
    ports:
      - "4200:80"
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
