stages:
  - integration_test
  
integration_test:
  stage: integration_test
  tags:
    - docker

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd integration_tests
    - curl -sS https://bootstrap.pypa.io/get-pip.py | python3

    - python3 -m pip install --upgrade pip
    - python3 -m pip install -r requirements.txt

    - export PATH=$HOME/.local/bin:$PATH
    - python3 -m pip show pytest
    
    - chmod +x init_project.sh
    - ./init_project.sh
    - docker images
    - docker volume ls
    - docker compose up --detach
    - pytest -s

  after_script:
    - echo Stopping all containers
    - docker stop $(docker ps -aq) && docker rm $(docker ps -aq)

    - echo Removing volumes
    - docker volume rm crew_config
    - docker volume rm crew_pgdata

