#!/usr/bin/env python3
"""
Simple webhook server for GitHub events.
Runs on port 8000, separate from MCP server.
"""
import os
import sys
import hmac
import hashlib
import logging
import asyncio
from fastapi import FastAPI, Request, HTTPException, BackgroundTasks
from fastapi.responses import JSONResponse
import uvicorn

sys.path.insert(0, '/app')

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

app = FastAPI(title="Git Agents Webhook")

WEBHOOK_SECRET = os.getenv('WEBHOOK_SECRET', '')


def verify_signature(payload: bytes, signature: str) -> bool:
    if not WEBHOOK_SECRET or not signature or not signature.startswith('sha256='):
        return not WEBHOOK_SECRET
    expected = 'sha256=' + hmac.new(WEBHOOK_SECRET.encode(), payload, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, signature)


async def run_agent(agent_name: str, pr_number: int):
    """Run agent for PR."""
    try:
        logger.info(f"Running {agent_name} for PR #{pr_number}")
        
        if agent_name == 'code_reviewer':
            from agents.code_reviewer.main import CodeReviewAgent
            from agents.code_reviewer.config import Config, Provider
            from shared.github_client import GitHubClient
            
            config = Config()
            client = GitHubClient(config.github_token, config.repo_owner, config.repo_name)
            agent = CodeReviewAgent()
            prs = await client.get_pull_requests([pr_number])
            if prs:
                await agent._process_pr(prs[0])
                
        elif agent_name == 'doc_support':
            from agents.doc_support.main import DocSupportAgent
            from agents.doc_support.config import Config
            from shared.github_client import GitHubClient
            
            config = Config()
            client = GitHubClient(config.github_token, config.repo_owner, config.repo_name)
            agent = DocSupportAgent()
            prs = await client.get_pull_requests([pr_number])
            if prs:
                await agent._process_pr(prs[0])
                
        elif agent_name == 'pr_summarizer':
            from agents.pr_summarizer.main import PRSummarizerAgent
            from agents.pr_summarizer.config import Config
            from shared.github_client import GitHubClient
            
            config = Config()
            client = GitHubClient(config.github_token, config.repo_owner, config.repo_name)
            agent = PRSummarizerAgent()
            prs = await client.get_pull_requests([pr_number])
            if prs:
                await agent._process_pr(prs[0])
        
        logger.info(f"✓ {agent_name} completed")
    except Exception as e:
        logger.error(f"✗ {agent_name} failed: {e}", exc_info=True)


async def check_release():
    """Check release notes."""
    try:
        from agents.release_notes.config import Config
        from shared.github_client import GitHubClient
        from agents.release_notes.main import ReleaseNotesAgent
        
        config = Config()
        client = GitHubClient(config.github_token, config.repo_owner, config.repo_name)
        merged_prs = await client.get_merged_since_last_release()
        
        if len(merged_prs) >= 3:
            logger.info(f"✓ Generating release notes for {len(merged_prs)} PRs")
            agent = ReleaseNotesAgent()
            release_type = agent._detect_release_type(merged_prs)
            notes = await agent.llm.generate_release_notes(merged_prs)
            await client.create_draft_release(f"{notes}\n\n---\n*Generated by AI*", release_type)
        else:
            logger.info(f"Skipping release notes ({len(merged_prs)} PRs)")
    except Exception as e:
        logger.error(f"Release check failed: {e}")


@app.get("/")
async def root():
    return {"service": "git-agents-webhook", "status": "running"}


@app.get("/health")
async def health():
    return {"status": "healthy"}


@app.post("/webhook/github")
async def webhook(request: Request, background_tasks: BackgroundTasks):
    signature = request.headers.get('X-Hub-Signature-256', '')
    body = await request.body()
    
    if WEBHOOK_SECRET and not verify_signature(body, signature):
        logger.warning("Invalid signature")
        raise HTTPException(401, "Invalid signature")
    
    try:
        payload = await request.json()
    except:
        raise HTTPException(400, "Invalid JSON")
    
    event = request.headers.get('X-GitHub-Event', '')
    logger.info(f"Webhook: {event}")
    
    if event == 'pull_request':
        action = payload.get('action')
        pr_num = payload.get('pull_request', {}).get('number')
        merged = payload.get('pull_request', {}).get('merged', False)
        
        logger.info(f"PR #{pr_num} - {action}, merged={merged}")
        
        if not pr_num:
            return {"status": "ignored"}
        
        if action == 'opened':
            background_tasks.add_task(run_agent, 'code_reviewer', pr_num)
            background_tasks.add_task(run_agent, 'doc_support', pr_num)
            background_tasks.add_task(run_agent, 'pr_summarizer', pr_num)
            return {"status": "accepted", "agents": ["code_reviewer", "doc_support", "pr_summarizer"]}
        
        elif action == 'synchronize':
            background_tasks.add_task(run_agent, 'code_reviewer', pr_num)
            return {"status": "accepted", "agents": ["code_reviewer"]}
        
        elif action == 'closed' and merged:
            background_tasks.add_task(check_release)
            return {"status": "accepted", "agents": ["release_notes_check"]}
    
    elif event == 'ping':
        return {"status": "pong", "message": "Webhook OK! 🎉"}
    
    return {"status": "ignored"}


if __name__ == "__main__":
    logger.info("Starting webhook server on port 8000")
    logger.info(f"Repository: {os.getenv('REPO_OWNER')}/{os.getenv('REPO_NAME')}")
    logger.info(f"Secret: {'✓' if WEBHOOK_SECRET else '✗'}")
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")