.build-multiarch-template:
  extends: .docker-login
  stage: build
  tags:
    - docker
  script:
    - export DOCKER_BUILDKIT=1
    - export BUILDER_NAME=multiarch-builder-${CI_PIPELINE_ID}-${CI_JOB_ID}

    - docker buildx create --use --name "$BUILDER_NAME"
    - docker buildx inspect --bootstrap
    - |
      docker buildx build \
        --platform linux/amd64,linux/arm64 \
        --build-arg BUILDKIT_INLINE_CACHE=1 \
        $EXTRA_BUILD_ARGS \
        --cache-from=type=registry,ref=$CACHE \
        --tag $TAG \
        --file $DOCKERFILE \
        $CONTEXT \
        --push

build-frontend:
  extends: .build-multiarch-template
  rules:
    - if: '$BUILD_STAGE == "skip"'
      when: never
    - if: '$FRONTEND_JOBS == "force"'
    - if: '$FRONTEND_JOBS == "skip"'
      when: never
    - if: '$FRONTEND_JOBS == "auto"'
      changes:
        - "frontend/**/*"
        - "integration_test/**/*"

  variables:
    REPO: $FRONTEND_REPO
    TAG: $TEST_FRONTEND_TAG
    CACHE: $CI_REGISTRY_IMAGE/frontend:latest-$CI_COMMIT_BRANCH
    DOCKERFILE: ./frontend/Dockerfile.fe
    CONTEXT: ./frontend
    EXTRA_BUILD_ARGS: ""

build-crewdb:
  extends: .build-multiarch-template
  rules:
    - if: '$BUILD_STAGE == "skip"'
      when: never
    - if: '$CREWDB_JOBS == "force"'
    - if: '$CREWDB_JOBS == "skip"'
      when: never
    - if: '$CREWDB_JOBS == "auto"'
      changes:
        - "src/crewdb/**/*"
        - "integration_test/**/*"

  variables:
    REPO: $CREWDB_REPO
    TAG: $TEST_CREWDB_TAG
    DOCKERFILE: ./src/crewdb/Dockerfile.crewdb
    CONTEXT: ./src/crewdb
    EXTRA_BUILD_ARGS: ""
    CACHE: $CI_REGISTRY_IMAGE/crewdb:latest-$CI_COMMIT_BRANCH

build-django:
  extends: .build-multiarch-template
  rules:
    - if: '$BUILD_STAGE == "skip"'
      when: never
    - if: '$DJANGO_JOBS == "force"'
    - if: '$DJANGO_JOBS == "skip"'
      when: never
    - if: '$DJANGO_JOBS == "auto"'
      changes:
        - "src/django_app/**/*"
        - "integration_test/**/*"

  variables:
    REPO: $DJANGO_REPO
    TAG: $TEST_DJANGO_TAG
    DOCKERFILE: ./src/django_app/Dockerfile.dj
    CONTEXT: ./src/django_app
    EXTRA_BUILD_ARGS: ""
    CACHE: $CI_REGISTRY_IMAGE/django:latest-$CI_COMMIT_BRANCH

build-manager:
  extends: .build-multiarch-template
  rules:
    - if: '$BUILD_STAGE == "skip"'
      when: never
    - if: '$MANAGER_JOBS == "force"'
    - if: '$MANAGER_JOBS == "skip"'
      when: never
    - if: '$MANAGER_JOBS == "auto"'
      changes:
        - "src/manager/**/*"
        - "src/tool/**/*"
        - "integration_test/**/*"

  variables:
    REPO: $MANAGER_REPO
    TAG: $TEST_MANAGER_TAG
    DOCKERFILE: ./src/manager/Dockerfile.man
    CONTEXT: ./src
    EXTRA_BUILD_ARGS: ""
    CACHE: $CI_REGISTRY_IMAGE/manager:latest-$CI_COMMIT_BRANCH

build-crew:
  extends: .build-multiarch-template
  rules:
    - if: '$BUILD_STAGE == "skip"'
      when: never
    - if: '$CREW_JOBS == "force"'
    - if: '$CREW_JOBS == "skip"'
      when: never
    - if: '$CREW_JOBS == "auto"'
      changes:
        - "src/crew/**/*"
        - "integration_test/**/*"

  variables:
    REPO: $CREW_REPO
    TAG: $TEST_CREW_TAG
    DOCKERFILE: ./src/crew/Dockerfile.crew
    CONTEXT: ./src
    EXTRA_BUILD_ARGS: ""
    CACHE: $CI_REGISTRY_IMAGE/crew:latest-$CI_COMMIT_BRANCH

build-sandbox:
  extends: .build-multiarch-template
  rules:
    - if: '$BUILD_STAGE == "skip"'
      when: never
    - if: '$SANDBOX_JOBS == "force"'
    - if: '$SANDBOX_JOBS == "skip"'
      when: never
    - if: '$SANDBOX_JOBS == "auto"'
      changes:
        - "src/sandbox/**/*"
        - "integration_test/**/*"

  variables:
    REPO: $SANDBOX_REPO
    TAG: $TEST_SANDBOX_TAG
    DOCKERFILE: ./src/sandbox/Dockerfile.sandbox
    CONTEXT: ./src
    EXTRA_BUILD_ARGS: ""
    CACHE: $CI_REGISTRY_IMAGE/sandbox:latest-$CI_COMMIT_BRANCH

build-knowledge:
  extends: .build-multiarch-template
  rules:
    - if: '$BUILD_STAGE == "skip"'
      when: never
    - if: '$KNOWLEDGE_JOBS == "force"'
    - if: '$KNOWLEDGE_JOBS == "skip"'
      when: never
    - if: '$KNOWLEDGE_JOBS == "auto"'
      changes:
        - "src/knowledge/**/*"
        - "integration_test/**/*"

  variables:
    REPO: $KNOWLEDGE_REPO
    TAG: $TEST_KNOWLEDGE_TAG
    DOCKERFILE: ./src/knowledge/Dockerfile.knowledge
    CONTEXT: ./src/knowledge
    EXTRA_BUILD_ARGS: ""
    CACHE: $CI_REGISTRY_IMAGE/knowledge:latest-$CI_COMMIT_BRANCH

build-realtime:
  extends: .build-multiarch-template
  rules:
    - if: '$BUILD_STAGE == "skip"'
      when: never
    - if: '$REALTIME_JOBS == "force"'
    - if: '$REALTIME_JOBS == "skip"'
      when: never
    - if: '$REALTIME_JOBS == "auto"'
      changes:
        - "src/realtime/**/*"
        - "integration_test/**/*"


  variables:
    REPO: $REALTIME_REPO
    TAG: $TEST_REALTIME_TAG
    DOCKERFILE: ./src/realtime/Dockerfile.realtime
    CONTEXT: ./src/realtime
    EXTRA_BUILD_ARGS: ""
    CACHE: $CI_REGISTRY_IMAGE/realtime:latest-$CI_COMMIT_BRANCH
