import asyncio
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from agents.release_notes.config import Config, Provider
from shared.github_client import GitHubClient
from shared.gitlab_client import GitLabClient
from shared.llm_client import LLMClient
from shared.cli_args import parse_pr_args, parse_release_args

class ReleaseNotesAgent:
    def __init__(self):
        self.config = Config()
        self.llm = LLMClient(self.config.openai_api_key, model="gpt-4o")
        
        if self.config.provider == Provider.GITHUB:
            self.client = GitHubClient(
                self.config.github_token,
                self.config.repo_owner,
                self.config.repo_name
            )
        else:
            self.client = GitLabClient(
                self.config.gitlab_token,
                self.config.gitlab_url,
                self.config.repo_owner,
                self.config.repo_name
            )
    
    async def run(self):
        pr_numbers, release_type = parse_release_args()
        
        if pr_numbers:
            print(f"Starting Release Notes Agent for PRs: {', '.join(map(str, pr_numbers))}")
            merged_prs = await self.client.get_pull_requests(pr_numbers)
        else:
            print("Starting Release Notes Agent for merged PRs...")
            merged_prs = await self.client.get_merged_since_last_release()
        
        if not merged_prs:
            print("No merged pull requests found")
            return
        
        if len(merged_prs) < 3 and not pr_numbers:
            print(f"Only {len(merged_prs)} merged PRs found, need at least 3 for release")
            return
        
        if not release_type:
            release_type = self._detect_release_type(merged_prs)
            print(f"Auto-detected release type: {release_type}")
        else:
            print(f"Manual release type: {release_type}")
        
        print(f"\nGenerating release notes for {len(merged_prs)} merged PRs...")
        notes = await self.llm.generate_release_notes(merged_prs)
        
        final_notes = f"{notes}\n\n---\n*Release notes generated by AI using GPT-4o*"
        
        await self.client.create_draft_release(final_notes, release_type)
        print("✓ Draft release created successfully")
    
    def _detect_release_type(self, prs: list) -> str:
        has_breaking = False
        has_feature = False
        
        breaking_keywords = ['breaking-change', 'breaking', 'major']
        feature_keywords = ['feature', 'feat', 'enhancement', 'new', 'minor']
        
        for pr in prs:
            labels = [label.lower() for label in pr.get('labels', [])]
            title = pr.get('title', '').lower()
            
            if any(keyword in labels or keyword in title for keyword in breaking_keywords):
                has_breaking = True
                break
            
            if any(keyword in labels or keyword in title for keyword in feature_keywords):
                has_feature = True
        
        if has_breaking:
            return 'major'
        elif has_feature:
            return 'minor'
        else:
            return 'patch'

if __name__ == "__main__":
    agent = ReleaseNotesAgent()
    asyncio.run(agent.run())