def format_checklist(issues):
    if not issues:
        return "## AI Code Review\n\nNo issues found - code looks good!\n\n*Generated by AI Code Review Agent using GPT-4o*"
    
    checklist = "## AI Code Review\n\n"
    for issue in issues:
        checklist += f"- [ ] {issue}\n"
    checklist += f"\n*Generated by AI Code Review Agent using GPT-4o*"
    return checklist