# Generated by Django 5.1.3 on 2025-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0120_webhooktrigger_session_entrypoint_webhooktriggernode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhooktriggernode",
            name="node_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
