# Generated by Django 5.1.3 on 2025-11-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0123_merge_20251105_1126"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentembedding",
            name="chunk",
        ),
        migrations.RemoveField(
            model_name="documentmetadata",
            name="document_content",
        ),
        migrations.RemoveField(
            model_name="documentembedding",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="documentembedding",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentmetadata",
            name="source_collection",
        ),
        migrations.RemoveField(
            model_name="sourcecollection",
            name="embedder",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="knowledge_collection",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="knowledge_collection",
        ),
        migrations.DeleteModel(
            name="Chunk",
        ),
        migrations.DeleteModel(
            name="DocumentContent",
        ),
        migrations.DeleteModel(
            name="DocumentEmbedding",
        ),
        migrations.DeleteModel(
            name="DocumentMetadata",
        ),
        migrations.DeleteModel(
            name="SourceCollection",
        ),
    ]
