# Generated by Django 5.1.3 on 2025-11-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0124_prepare_for_knowledge_refactor"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                ("document_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pdf", "Pdf"),
                            ("csv", "Csv"),
                            ("docx", "Docx"),
                            ("txt", "Txt"),
                            ("json", "Json"),
                            ("html", "Html"),
                            ("md", "Md"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="Size in bytes", null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.BinaryField(
                        default=999, help_text="Binary file content (max 12MB)"
                    ),
                ),
                (
                    "document_metadata",
                    models.OneToOneField(
                        default=999,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="tables.documentmetadata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SourceCollection",
            fields=[
                ("collection_id", models.AutoField(primary_key=True, serialize=False)),
                ("collection_name", models.CharField(blank=True, max_length=255)),
                (
                    "user_id",
                    models.CharField(blank=True, default="dummy_user", max_length=120),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("empty", "Empty"),
                            ("uploading", "Uploading"),
                            ("completed", "Completed"),
                            ("warning", "Warning"),
                        ],
                        default="empty",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "collection_name"),
                        name="unique_collection_name_per_user",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="documentmetadata",
            name="source_collection",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="tables.sourcecollection",
            ),
        ),
        migrations.CreateModel(
            name="BaseRagType",
            fields=[
                ("rag_type_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rag_type",
                    models.CharField(
                        choices=[("naive", "Naive"), ("graph", "Graph")], max_length=30
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_types",
                        to="tables.sourcecollection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="agent",
            name="knowledge_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="knowledge_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tables.sourcecollection",
            ),
        ),
        migrations.AddIndex(
            model_name="documentmetadata",
            index=models.Index(
                fields=["source_collection"], name="tables_docu_source__eec4f1_idx"
            ),
        ),
    ]
