# Generated by Django 5.1.3 on 2025-11-11 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0125_refactor_knowledge_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentcontent",
            name="content",
            field=models.BinaryField(help_text="Binary file content (max 12MB)"),
        ),
        migrations.AlterField(
            model_name="documentcontent",
            name="document_metadata",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content",
                to="tables.documentmetadata",
            ),
        ),
    ]
