# Generated by Django 5.1.3 on 2025-12-01 08:58

from django.db import migrations, models


def set_quickstart_status(apps, schema_editor):
    """Set quickstart_completed to True if any LLMConfig exists."""
    QuickstartStatus = apps.get_model("tables", "QuickstartStatus")
    LLMConfig = apps.get_model("tables", "LLMConfig")

    llm_exists = LLMConfig.objects.exists()

    QuickstartStatus.objects.update_or_create(
        singleton=True,
        defaults={"quickstart_completed": llm_exists},
    )


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0126_alter_webhooktriggernode_graph"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickstartStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("singleton", models.BooleanField(default=True, unique=True)),
                ("quickstart_completed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(
            set_quickstart_status, reverse_code=migrations.RunPython.noop
        ),
    ]
