# Generated by Django 5.1.3 on 2025-11-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0126_alter_webhooktriggernode_graph"),
    ]

    operations = [
        migrations.CreateModel(
            name="PythonCodeToolConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("configuration", models.JSONField(default=dict)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tables.pythoncodetool",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PythonCodeToolConfigField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("llm_config", "Llm Config"),
                            ("embedding_config", "Embedding Config"),
                            ("string", "String"),
                            ("boolean", "Boolean"),
                            ("any", "Any"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                        ],
                        default="string",
                        max_length=255,
                    ),
                ),
                ("default_value", models.JSONField(blank=True, null=True)),
                ("required", models.BooleanField(default=True)),
                ("secret", models.BooleanField(default=False)),
                (
                    "tool",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_fields",
                        to="tables.pythoncodetool",
                    ),
                ),
            ],
            options={
                "unique_together": {("tool", "name")},
            },
        ),
    ]
