# Generated by Django 5.1.3 on 2025-11-11 15:37

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0126_alter_documentcontent_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NaiveRag",
            fields=[
                ("naive_rag_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rag_status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("warning", "Warning"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_rag_type",
                    models.ForeignKey(
                        limit_choices_to={"rag_type": "naive"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naive_rags",
                        to="tables.baseragtype",
                    ),
                ),
                (
                    "embedder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tables.embeddingconfig",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NaiveRagDocumentConfig",
            fields=[
                (
                    "naive_rag_document_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "chunk_strategy",
                    models.CharField(
                        choices=[
                            ("token", "Token"),
                            ("character", "Character"),
                            ("markdown", "Markdown"),
                            ("json", "Json"),
                            ("html", "Html"),
                            ("csv", "Csv"),
                        ],
                        default="token",
                        max_length=20,
                    ),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Size of each chunk (tokens or characters)",
                    ),
                ),
                (
                    "chunk_overlap",
                    models.PositiveIntegerField(
                        default=150, help_text="Overlap between consecutive chunks"
                    ),
                ),
                (
                    "additional_params",
                    models.JSONField(
                        default=dict,
                        help_text="Strategy-specific params (e.g., separators, headers)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("chunked", "Chunked"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("warning", "Warning"),
                            ("failed", "Failed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naive_rag_document_config",
                        to="tables.documentmetadata",
                    ),
                ),
                (
                    "naive_rag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="naive_rag_configs",
                        to="tables.naiverag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NaiveRagChunk",
            fields=[
                ("chunk_id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        help_text="Order of this chunk in the document"
                    ),
                ),
                ("token_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Chunk-specific metadata (page numbers, sections, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "naive_rag_document_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="tables.naiveragdocumentconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="NaiveRagEmbedding",
            fields=[
                (
                    "embedding_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vector", pgvector.django.vector.VectorField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chunk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="tables.naiveragchunk",
                    ),
                ),
                (
                    "naive_rag_document_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="tables.naiveragdocumentconfig",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="naiveragdocumentconfig",
            index=models.Index(
                fields=["naive_rag", "status"], name="tables_naiv_naive_r_f3bcf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="naiveragdocumentconfig",
            index=models.Index(
                fields=["document"], name="tables_naiv_documen_254ff9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="naiveragdocumentconfig",
            constraint=models.UniqueConstraint(
                fields=("naive_rag", "document"), name="unique_document_per_naive_rag"
            ),
        ),
        migrations.AddIndex(
            model_name="naiveragchunk",
            index=models.Index(
                fields=["naive_rag_document_config", "chunk_index"],
                name="tables_naiv_naive_r_343843_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="naiveragchunk",
            constraint=models.UniqueConstraint(
                fields=("naive_rag_document_config", "chunk_index"),
                name="unique_chunk_index_per_naive_rag_document_config",
            ),
        ),
        migrations.AddIndex(
            model_name="naiveragembedding",
            index=models.Index(
                fields=["naive_rag_document_config"],
                name="tables_naiv_naive_r_e7ad19_idx",
            ),
        ),
    ]
