# Generated by Django 5.1.3 on 2025-12-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0127_pythoncodetoolconfig_agentpythoncodetoolconfigs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pythoncodetoolconfigfield",
            name="default_value",
        ),
        migrations.AlterField(
            model_name="pythoncodetoolconfigfield",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
