# Generated by Django 5.1.3 on 2025-11-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0127_sourcecollection_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebScraperKnowledgeNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(blank=True, max_length=255)),
                ("input_map", models.JSONField(default=dict)),
                (
                    "output_variable_path",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_scraper_knowledge_node_list",
                        to="tables.graph",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("graph", "node_name"),
                        name="unique_graph_node_name_for_web_scraper_knowledge_node",
                    )
                ],
            },
        ),
    ]
