# Generated by Django 5.1.3 on 2025-11-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0127_naive_rag_type_implementation"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcecollection",
            name="collection_origin",
            field=models.CharField(
                choices=[("user", "User"), ("node", "Node"), ("tool", "Tool")],
                default="user",
                max_length=20,
            ),
        ),
    ]
