# Generated by Django 5.1.3 on 2025-12-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0128_pythoncodetoolconfig_agentpythoncodetoolconfigs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="condition",
            name="ui_condition",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="condition",
            name="condition",
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name="conditiongroup",
            name="ui_expression",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="conditiongroup",
            name="ui_manipulation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="conditiongroup",
            name="expression",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="conditiongroup",
            name="manipulation",
            field=models.TextField(default=None, null=True),
        ),
    ]
