# Generated by Django 5.1.3 on 2025-12-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0127_quickstartstatus"),
        ("tables", "0128_pythoncodetoolconfig_agentpythoncodetoolconfigs_and_more"),
    ]

    operations = []
