# Generated by Django 5.1.3 on 2025-12-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0128_remove_pythoncodetoolconfigfield_default_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pythoncodetoolconfigfield",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="pythoncodetoolconfig",
            unique_together={("tool", "name")},
        ),
    ]
