# Generated by Django 5.1.3 on 2025-12-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0128_webscraperknowledgenode"),
    ]

    operations = [
        migrations.AddField(
            model_name="webscraperknowledgenode",
            name="collection_name",
            field=models.CharField(default="default_collection", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webscraperknowledgenode",
            name="embedder",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="webscraperknowledgenode",
            name="time_to_expired",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
