# Generated by Django 5.1.3 on 2025-11-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0128_sourcecollection_collection_origin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentcontent",
            name="document_metadata",
        ),
        migrations.AddField(
            model_name="documentmetadata",
            name="document_content",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata_records",
                to="tables.documentcontent",
            ),
        ),
    ]
