# Generated by Django 5.1.3 on 2026-01-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0129_merge_20251229_1542"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="token_usage",
            field=models.JSONField(default=dict),
        ),
    ]
