# Generated by Django 5.1.3 on 2025-12-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0129_condition_ui_condition_alter_condition_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="ui_condition",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="conditiongroup",
            name="ui_expression",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="conditiongroup",
            name="ui_manipulation",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
