# Generated by Django 5.1.3 on 2026-01-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0129_merge_20251229_1542"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentembedding",
            name="chunk",
        ),
        migrations.RemoveField(
            model_name="documentmetadata",
            name="document_content",
        ),
        migrations.RemoveField(
            model_name="documentembedding",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="documentembedding",
            name="document",
        ),
        migrations.RemoveField(
            model_name="documentmetadata",
            name="source_collection",
        ),
        migrations.RemoveField(
            model_name="sourcecollection",
            name="embedder",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="knowledge_collection",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="knowledge_collection",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="agent",
            name="similarity_threshold",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="crew",
            name="similarity_threshold",
        ),
        migrations.RemoveField(
            model_name="defaultrealtimeagentconfig",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="defaultrealtimeagentconfig",
            name="similarity_threshold",
        ),
        migrations.RemoveField(
            model_name="realtimeagent",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="realtimeagent",
            name="similarity_threshold",
        ),
        migrations.RemoveField(
            model_name="realtimeagentchat",
            name="search_limit",
        ),
        migrations.RemoveField(
            model_name="realtimeagentchat",
            name="similarity_threshold",
        ),
        migrations.DeleteModel(
            name="Chunk",
        ),
        migrations.DeleteModel(
            name="DocumentContent",
        ),
        migrations.DeleteModel(
            name="DocumentEmbedding",
        ),
        migrations.DeleteModel(
            name="DocumentMetadata",
        ),
        migrations.DeleteModel(
            name="SourceCollection",
        ),
    ]
