# Generated by Django 5.1.3 on 2025-12-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0123_merge_20251030_1636"),
        ("tables", "0123_merge_20251031_1745"),
        ("tables", "0126_merge_20251113_1040"),
        ("tables", "0127_fix_graphsessionmessage_cascade"),
        ("tables", "0129_alter_pythoncodetoolconfigfield_name_and_more"),
    ]

    operations = []
