# Generated by Django 5.1.3 on 2025-12-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0130_merge_20251205_1318"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webscraperknowledgenode",
            name="time_to_expired",
            field=models.IntegerField(blank=True),
        ),
    ]
