# Generated by Django 5.1.3 on 2025-12-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0131_alter_webscraperknowledgenode_time_to_expired"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webscraperknowledgenode",
            name="time_to_expired",
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
