# Generated by Django 5.1.3 on 2026-01-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0133_restore_knowledge_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="naiveragdocumentconfig",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("chunking", "Chunking"),
                    ("chunked", "Chunked"),
                    ("indexing", "Indexing"),
                    ("completed", "Completed"),
                    ("warning", "Warning"),
                    ("failed", "Failed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NaiveRagPreviewChunk",
            fields=[
                (
                    "preview_chunk_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("text", models.TextField()),
                (
                    "chunk_index",
                    models.PositiveIntegerField(
                        help_text="Order of this chunk in the document"
                    ),
                ),
                ("token_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Chunk-specific metadata (page numbers, sections, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "naive_rag_document_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_chunks",
                        to="tables.naiveragdocumentconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index"],
                "indexes": [
                    models.Index(
                        fields=["naive_rag_document_config", "chunk_index"],
                        name="tables_naiv_naive_r_202e85_idx",
                    )
                ],
            },
        ),
    ]
