# Generated by Django 5.1.3 on 2026-01-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0134_merge_20260121_1243"),
        ("tables", "0134_merge_20260122_1025"),
    ]

    operations = []
