# Generated by Django 5.1.3 on 2026-01-26 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0135_sessionwarningmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionwarningmessage",
            name="session",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warnings",
                to="tables.session",
            ),
        ),
    ]
