# Generated by Django 5.1.3 on 2026-01-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0130_alter_condition_ui_condition_and_more"),
        ("tables", "0136_merge_20260126_1313"),
    ]

    operations = []
