# 0147_edge_keys_and_decision_data.py
# Generated by Django 5.1.3 on 2026-02-18 11:19

from django.db import migrations, models

def migrate_edges_data(apps, schema_editor):
    """
    Переносит данные из строковых ключей (start_key/end_key/source/next_node)
    в новые числовые или строковые поля ID.
    """
    Graph = apps.get_model('tables', 'Graph')
    Edge = apps.get_model('tables', 'Edge')
    ConditionalEdge = apps.get_model('tables', 'ConditionalEdge')
    DecisionTableNode = apps.get_model('tables', 'DecisionTableNode')
    ConditionGroup = apps.get_model('tables', 'ConditionGroup')

    # Список всех моделей, которые являются нодами
    node_models = [
        apps.get_model('tables', 'CrewNode'),
        apps.get_model('tables', 'PythonNode'),
        apps.get_model('tables', 'FileExtractorNode'),
        apps.get_model('tables', 'AudioTranscriptionNode'),
        apps.get_model('tables', 'LLMNode'),
        apps.get_model('tables', 'EndNode'),
        apps.get_model('tables', 'SubGraphNode'),
        apps.get_model('tables', 'StartNode'),
        apps.get_model('tables', 'DecisionTableNode'),
        apps.get_model('tables', 'WebhookTriggerNode'),
        apps.get_model('tables', 'TelegramTriggerNode'),
    ]

    for graph in Graph.objects.all():
        # 1. Строим карту { "node_name": id } для ТЕКУЩЕГО графа
        name_to_id_map = {}

        for model in node_models:
            # Надежная проверка наличия поля 'node_name' у модели
            has_node_name = any(f.name == 'node_name' for f in model._meta.fields)
            
            if has_node_name:
                nodes = model.objects.filter(graph_id=graph.id).values('id', 'node_name')
            else:
                nodes = model.objects.filter(graph_id=graph.id).values('id')
            
            for node in nodes:
                node_id = node['id']
                name_to_id_map[str(node_id)] = node_id  # Map "105" -> 105
                
                if 'node_name' in node and node['node_name']:
                    name_to_id_map[node['node_name']] = node_id

        # Особый случай: StartNode
        StartNode = apps.get_model('tables', 'StartNode')
        start_node = StartNode.objects.filter(graph_id=graph.id).first()
        if start_node:
            name_to_id_map['__start__'] = start_node.id

        # 2. Обновляем Edges
        edges_to_update = []
        for edge in Edge.objects.filter(graph_id=graph.id):
            start_id = name_to_id_map.get(edge.start_key)
            end_id = name_to_id_map.get(edge.end_key)

            if start_id and end_id:
                edge.start_node_id = start_id
                edge.end_node_id = end_id
                edges_to_update.append(edge)
            else:
                print(f"Warning: Could not map Edge in Graph {graph.id}: {edge.start_key} -> {edge.end_key}")

        if edges_to_update:
            Edge.objects.bulk_update(edges_to_update, ['start_node_id', 'end_node_id'])

        # 3. Обновляем Conditional Edges
        cond_edges_to_update = []
        for c_edge in ConditionalEdge.objects.filter(graph_id=graph.id):
            source_id = name_to_id_map.get(c_edge.source)
            if source_id:
                c_edge.source_node_id = source_id
                cond_edges_to_update.append(c_edge)
            else:
                print(f"Warning: Could not map ConditionalEdge in Graph {graph.id}: source {c_edge.source}")

        if cond_edges_to_update:
            ConditionalEdge.objects.bulk_update(cond_edges_to_update, ['source_node_id'])

        # 4. Обновляем DecisionTableNode
        dt_nodes_to_update = []
        for dt_node in DecisionTableNode.objects.filter(graph_id=graph.id):
            updated = False
            if dt_node.default_next_node:
                new_id = name_to_id_map.get(dt_node.default_next_node)
                if new_id:
                    dt_node.default_next_node_id = str(new_id)
                    updated = True
            if dt_node.next_error_node:
                new_id = name_to_id_map.get(dt_node.next_error_node)
                if new_id:
                    dt_node.next_error_node_id = str(new_id)
                    updated = True
            if updated:
                dt_nodes_to_update.append(dt_node)
                
        if dt_nodes_to_update:
            DecisionTableNode.objects.bulk_update(dt_nodes_to_update, ['default_next_node_id', 'next_error_node_id'])

        # 5. Обновляем ConditionGroup
        cg_to_update = []
        for cg in ConditionGroup.objects.filter(decision_table_node__graph_id=graph.id):
            if cg.next_node:
                new_id = name_to_id_map.get(cg.next_node)
                if new_id:
                    cg.next_node_id = str(new_id)
                    cg_to_update.append(cg)
                    
        if cg_to_update:
            ConditionGroup.objects.bulk_update(cg_to_update, ['next_node_id'])


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("tables", "0146_alter_audiotranscriptionnode_id_alter_crewnode_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='start_node_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='end_node_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='source_node_id',
            field=models.BigIntegerField(null=True),
        ),
        
        migrations.AddField(
            model_name='decisiontablenode',
            name='default_next_node_id',
            field=models.CharField(max_length=255, null=True, blank=True, default=None),
        ),
        migrations.AddField(
            model_name='decisiontablenode',
            name='next_error_node_id',
            field=models.CharField(max_length=255, null=True, blank=True, default=None),
        ),
        migrations.AddField(
            model_name='conditiongroup',
            name='next_node_id',
            field=models.CharField(max_length=255, null=True, blank=True, default=None),
        ),

        migrations.RemoveField(
            model_name='conditionaledge',
            name='then',
        ),

        migrations.RunPython(migrate_edges_data, reverse_migration),

        migrations.AlterField(
            model_name='edge',
            name='start_node_id',
            field=models.BigIntegerField(null=False, default=0),
        ),
        migrations.AlterField(
            model_name='edge',
            name='end_node_id',
            field=models.BigIntegerField(null=False, default=0), 
        ),
        migrations.AlterField(
            model_name='conditionaledge',
            name='source_node_id',
            field=models.BigIntegerField(null=False, default=0),
        ),
    ]