# Generated by Django 5.1.3 on 2026-02-18 11:19

from django.db import migrations, models

def migrate_edges_data(apps, schema_editor):
    """
    Переносит данные из строковых ключей (start_key/end_key/source)
    в новые числовые поля ID (start_node_id/end_node_id/source_node_id).
    """
    Graph = apps.get_model('tables', 'Graph')
    Edge = apps.get_model('tables', 'Edge')
    ConditionalEdge = apps.get_model('tables', 'ConditionalEdge')

    # Список всех моделей, которые являются нодами
    node_models = [
        apps.get_model('tables', 'CrewNode'),
        apps.get_model('tables', 'PythonNode'),
        apps.get_model('tables', 'FileExtractorNode'),
        apps.get_model('tables', 'AudioTranscriptionNode'),
        apps.get_model('tables', 'LLMNode'),
        apps.get_model('tables', 'EndNode'),
        apps.get_model('tables', 'SubGraphNode'),
        apps.get_model('tables', 'StartNode'),
        apps.get_model('tables', 'DecisionTableNode'),
        apps.get_model('tables', 'WebhookTriggerNode'),
        apps.get_model('tables', 'TelegramTriggerNode'),
    ]

    # Обрабатываем граф за графом, чтобы не грузить память
    for graph in Graph.objects.all():
        # 1. Строим карту { "node_name": id } для ТЕКУЩЕГО графа
        #    Также добавляем маппинг по строковому представлению ID (на случай если keys уже ID)
        name_to_id_map = {}

        for model in node_models:
            # Берем только ноды этого графа
            nodes = model.objects.filter(graph_id=graph.id).values('id', 'node_name') if hasattr(model, 'node_name') else model.objects.filter(graph_id=graph.id).values('id')
            
            for node in nodes:
                node_id = node['id']
                name_to_id_map[str(node_id)] = node_id  # Map "105" -> 105
                
                # Если у ноды есть имя, маппим имя -> id
                if 'node_name' in node and node['node_name']:
                    name_to_id_map[node['node_name']] = node_id

        # Особый случай: StartNode часто имеет ключ "__start__" во фронтенде
        start_node = apps.get_model('tables', 'StartNode').objects.filter(graph_id=graph.id).first()
        if start_node:
            name_to_id_map['__start__'] = start_node.id

        # 2. Обновляем обычные Edges
        edges_to_update = []
        for edge in Edge.objects.filter(graph_id=graph.id):
            start_id = name_to_id_map.get(edge.start_key)
            end_id = name_to_id_map.get(edge.end_key)

            if start_id and end_id:
                edge.start_node_id = start_id
                edge.end_node_id = end_id
                edges_to_update.append(edge)
            else:
                print(f"Warning: Could not map Edge in Graph {graph.id}: {edge.start_key} -> {edge.end_key}")

        if edges_to_update:
            Edge.objects.bulk_update(edges_to_update, ['start_node_id', 'end_node_id'])

        # 3. Обновляем Conditional Edges
        cond_edges_to_update = []
        for c_edge in ConditionalEdge.objects.filter(graph_id=graph.id):
            source_id = name_to_id_map.get(c_edge.source)
            
            if source_id:
                c_edge.source_node_id = source_id
                cond_edges_to_update.append(c_edge)
            else:
                print(f"Warning: Could not map ConditionalEdge in Graph {graph.id}: source {c_edge.source}")

        if cond_edges_to_update:
            ConditionalEdge.objects.bulk_update(cond_edges_to_update, ['source_node_id'])


def reverse_migration(apps, schema_editor):
    """
    Обратная миграция не требуется, так как мы не удаляем данные,
    а только заполняем новые поля.
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0146_alter_audiotranscriptionnode_id_alter_crewnode_id_and_more"),
    ]

    operations = [
        # (nullable)
        migrations.AddField(
            model_name='edge',
            name='start_node_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='edge',
            name='end_node_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conditionaledge',
            name='source_node_id',
            field=models.BigIntegerField(null=True),
        ),

        # 2. Удаляем поле 'then' из ConditionalEdge (как вы просили ранее)
        migrations.RemoveField(
            model_name='conditionaledge',
            name='then',
        ),

        # 3. Запускаем Python-скрипт для переноса данных
        migrations.RunPython(migrate_edges_data, reverse_migration),


        migrations.AlterField(
            model_name='edge',
            name='start_node_id',
            field=models.BigIntegerField(null=False, default=0),
        ),
        migrations.AlterField(
            model_name='edge',
            name='end_node_id',
            field=models.BigIntegerField(null=False, default=0), 
        ),
        migrations.AlterField(
            model_name='conditionaledge',
            name='source_node_id',
            field=models.BigIntegerField(null=False, default=0),
        ),
    ]
