# Generated by Django 5.1.3 on 2026-04-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0155_merge_20260317_1513"),
        ("tables", "0167_merge_20260410_1240"),
    ]

    operations = []
