# Generated by Django 5.1.3 on 2026-04-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0164_scheduletriggernode"),
        ("tables", "0169_merge_imp_auth"),
    ]

    operations = []
