# Generated by Django 5.1.3 on 2026-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0170_merge_0164_scheduletriggernode_0169_merge_imp_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduletriggernode",
            name="timezone",
            field=models.CharField(blank=True, default="UTC", max_length=64),
        ),
        migrations.AlterField(
            model_name="scheduletriggernode",
            name="end_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("never", "Never"),
                    ("on_date", "On Date"),
                    ("after_n_runs", "After N Runs"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduletriggernode",
            name="run_mode",
            field=models.CharField(
                blank=True,
                choices=[("once", "Once"), ("repeat", "Repeat")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="scheduletriggernode",
            name="start_date_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
