# Generated by Django 5.1.3 on 2026-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0171_scheduletriggernode_timezone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduletriggernode",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
