# Generated by Django 5.1.3 on 2026-05-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0171_scheduletriggernode_timezone_and_more"),
        ("tables", "0174_merge_20260429_1147"),
    ]

    operations = []
