# Generated by Django 5.1.3 on 2026-05-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0175_merge_20260504_1000"),
        ("tables", "0176_create_schedule_trigger_node"),
    ]

    operations = []
