# Generated by Django 5.1.3 on 2026-05-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0176_merge_organizations_migrations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentgraphrag",
            name="search_method",
            field=models.CharField(
                choices=[
                    ("basic", "Basic Search"),
                    ("local", "Local Search"),
                    ("global_search", "Global Search"),
                ],
                default="basic",
                help_text="Active search method: basic, local or global_search",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="GraphRagGlobalSearchConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "map_prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The global search mapper prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "reduce_prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The global search reducer prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "knowledge_prompt",
                    models.TextField(
                        blank=True,
                        default=None,
                        help_text="The global search general prompt to use.",
                        null=True,
                    ),
                ),
                (
                    "max_context_tokens",
                    models.IntegerField(
                        default=12000, help_text="The maximum context size in tokens."
                    ),
                ),
                (
                    "data_max_tokens",
                    models.IntegerField(
                        default=12000, help_text="The data llm maximum tokens."
                    ),
                ),
                (
                    "map_max_length",
                    models.IntegerField(
                        default=1000,
                        help_text="The map llm maximum response length in words.",
                    ),
                ),
                (
                    "reduce_max_length",
                    models.IntegerField(
                        default=2000,
                        help_text="The reduce llm maximum response length in words.",
                    ),
                ),
                (
                    "dynamic_community_selection",
                    models.BooleanField(
                        default=False,
                        help_text="Enable dynamic community selection at query time.",
                    ),
                ),
                (
                    "dynamic_search_threshold",
                    models.IntegerField(
                        default=1,
                        help_text="Rating threshold to include a community report.",
                    ),
                ),
                (
                    "dynamic_search_keep_parent",
                    models.BooleanField(
                        default=False,
                        help_text="Keep parent community if any of the child communities are relevant.",
                    ),
                ),
                (
                    "dynamic_search_num_repeats",
                    models.IntegerField(
                        default=1,
                        help_text="Number of times to rate the same community report.",
                    ),
                ),
                (
                    "dynamic_search_use_summary",
                    models.BooleanField(
                        default=False,
                        help_text="Use community summary instead of full_context.",
                    ),
                ),
                (
                    "dynamic_search_max_level",
                    models.IntegerField(
                        default=2,
                        help_text="The maximum level of community hierarchy to consider if none of the processed communities are relevant.",
                    ),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        help_text="Agent this global search configuration belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_global_search_config",
                        to="tables.agent",
                    ),
                ),
            ],
            options={
                "db_table": "graph_rag_global_search_config",
            },
        ),
    ]
