# Generated by Django 5.1.3 on 2026-05-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0176_create_schedule_trigger_node"),
        ("tables", "0177_merge_20260515_1407"),
    ]

    operations = []
