# Generated by Django 5.1.3 on 2026-05-15 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0176_merge_organizations_migrations"),
        ("tables", "0177_merge_python_node_and_schedule_trigger"),
    ]

    operations = []
