#!/bin/bash
# setup_prod.sh — Interactively fill in required production variables into src/prod.env

PROD_ENV="src/prod.env"
BASE_ENV="src/.env"

# Load already-set values from prod.env into associative array
declare -A CURRENT
if [ -f "$PROD_ENV" ]; then
    while IFS='=' read -r key value; do
        [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
        CURRENT["$key"]="$value"
    done < "$PROD_ENV"
fi

# Load base .env for reference (won't overwrite prod.env values)
declare -A BASE
if [ -f "$BASE_ENV" ]; then
    while IFS='=' read -r key value; do
        [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
        BASE["$key"]="$value"
    done < "$BASE_ENV"
fi

declare -A ANSWERS

ask() {
    local key="$1"
    local description="$2"
    local required="${3:-true}"

    # Already set in prod.env — skip
    if [ -n "${CURRENT[$key]}" ]; then
        ANSWERS["$key"]="${CURRENT[$key]}"
        echo "  ✓ $key (already set)"
        return
    fi

    local base_val="${BASE[$key]:-}"
    local prompt="  $key — $description"
    [ -n "$base_val" ] && prompt="$prompt [current: $base_val]"
    [ "$required" = "false" ] && prompt="$prompt (optional, Enter to skip)"
    echo ""
    echo "$prompt"
    read -r -p "  > " input

    if [ -n "$input" ]; then
        ANSWERS["$key"]="$input"
    elif [ "$required" = "false" ]; then
        ANSWERS["$key"]=""
    else
        echo "  ⚠ Required. Using base .env value: $base_val"
        ANSWERS["$key"]="$base_val"
    fi
}

echo "============================================"
echo "  Production environment setup → $PROD_ENV"
echo "============================================"
echo "Press Enter to keep existing values."
echo ""

echo "--- Security ---"
ask "SECRET_KEY"          "Django secret key (generate: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\")"
ask "POSTGRES_PASSWORD"   "PostgreSQL password"
ask "REDIS_PASSWORD"      "Redis password"
ask "DB_REALTIME_PASSWORD" "Realtime DB user password"
ask "DB_MANAGER_PASSWORD"  "Manager DB user password"
ask "DB_CREW_PASSWORD"     "Crew DB user password"
ask "DB_KNOWLEDGE_PASSWORD" "Knowledge DB user password"

echo ""
echo "--- Domain & SSL ---"
ask "DOMAIN_NAME"    "Production domain name (e.g. example.com)"
ask "ALLOWED_HOSTS"  "Django ALLOWED_HOSTS (e.g. example.com,www.example.com)"
ask "API_URL"        "Frontend API URL (e.g. https://example.com/api/)"
ask "REALTIME_API_URL" "Frontend Realtime API URL (e.g. https://example.com/realtime/)"
ask "SSL_ENABLE"     "SSL enable flag: empty string '' = enabled, '#' = disabled"

echo ""
echo "--- Voice / Twilio (optional) ---"
ask "TWILIO_ACCOUNT_SID" "Twilio Account SID"         "false"
ask "TWILIO_AUTH_TOKEN"  "Twilio Auth Token"           "false"
ask "VOICE_AGENT_ID"     "RealtimeAgent ID for voice"  "false"
ask "VOICE_STREAM_URL"   "WebSocket URL for Twilio MediaStream (e.g. wss://example.com/voice/stream)" "false"

echo ""
echo "--- Infrastructure ---"
ask "CREW_SAVEFILES_PATH" "Host path for crew savefiles (e.g. /home/user/savefiles)"

# Write prod.env
{
    echo "# Production overrides — generated by make_scripts/setup_prod.sh"
    echo "# $(date '+%Y-%m-%d %H:%M:%S')"
    echo ""
    echo "# Security"
    for key in SECRET_KEY POSTGRES_PASSWORD REDIS_PASSWORD DB_REALTIME_PASSWORD DB_MANAGER_PASSWORD DB_CREW_PASSWORD DB_KNOWLEDGE_PASSWORD; do
        [ -n "${ANSWERS[$key]}" ] && echo "$key=${ANSWERS[$key]}"
    done
    echo ""
    echo "# Domain & SSL"
    for key in DOMAIN_NAME ALLOWED_HOSTS API_URL REALTIME_API_URL SSL_ENABLE; do
        [ "${ANSWERS[$key]+_}" ] && echo "$key=${ANSWERS[$key]}"
    done
    echo ""
    echo "# Voice"
    for key in TWILIO_ACCOUNT_SID TWILIO_AUTH_TOKEN VOICE_AGENT_ID VOICE_STREAM_URL; do
        [ -n "${ANSWERS[$key]}" ] && echo "$key=${ANSWERS[$key]}"
    done
    echo ""
    echo "# Infrastructure"
    for key in CREW_SAVEFILES_PATH; do
        [ -n "${ANSWERS[$key]}" ] && echo "$key=${ANSWERS[$key]}"
    done
} > "$PROD_ENV"

echo ""
echo "============================================"
echo "  Saved to $PROD_ENV"
echo "============================================"
