duck_duck_search:
  tool_class_name: !callable DuckDuckGoSearchRun

brave_search:
  tool_class_name: !callable Brave
  kwargs:
    api_token: !var API_TOKEN
  dependencies:
    - brave-oauth-lib
    - crewai

wolfram_alpha:
  tool_class_name: !callable WolframAlphaQueryRun
  kwargs:
    api_token: !var WOLFRAM_API_KEY
    api_wrapper: !callable WolframAlphaAPIWrapper
  dependencies:
    - asyncio
    - aiohttp