DuckDuckGoSearchRun: langchain_community.tools.ddg_search.tool.DuckDuckGoSearchRun
TavilySearchResults: langchain_community.tools.tavily_search.tool.TavilySearchResults
WolframAlphaQuery: "some.path.to.wolfram.tool"
