duck_duck_search:
  tool_class_name: DuckDuckGoSearchRun

wolfram_alpha:
  tool_class_name: WolframAlphaQueryRun
  kwargs:
    api_wrapper: !callable 
      callable_name: WolframAlphaAPIWrapper
      kwargs:
        wolfram_alpha_appid: "123"
  dependencies:
    - wolframalpha