import asyncio
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from agents.code_reviewer.config import Config, Provider
from shared.github_client import GitHubClient
from shared.gitlab_client import GitLabClient
from shared.llm_client import LLMClient
from shared.cli_args import parse_pr_args

class CodeReviewAgent:
    def __init__(self):
        self.config = Config()
        self.llm = LLMClient(self.config.openai_api_key, model="gpt-4o")
        
        if self.config.provider == Provider.GITHUB:
            self.client = GitHubClient(
                self.config.github_token, 
                self.config.repo_owner, 
                self.config.repo_name
            )
        else:
            self.client = GitLabClient(
                self.config.gitlab_token,
                self.config.gitlab_url,
                self.config.repo_owner,
                self.config.repo_name
            )
    
    async def run(self):
        pr_numbers = parse_pr_args()
        
        if pr_numbers:
            print(f"Starting Code Review Agent for PRs: {', '.join(map(str, pr_numbers))}")
        else:
            print("Starting Code Review Agent for all open PRs...")
        
        prs = await self.client.get_pull_requests(pr_numbers)
        
        if not prs:
            print("No pull requests found")
            return
        
        for pr in prs:
            await self._process_pr(pr)
    
    async def _process_pr(self, pr):
        print(f"\n{'='*60}")
        print(f"Analyzing PR #{pr['id']}: {pr['title']}")
        print(f"{'='*60}")
        
        diff = await self.client.get_diff(pr['id'])
        files = await self.client.get_changed_files(pr['id'])
        
        if not diff.strip():
            print("No diff found, skipping...")
            return
        
        pr_context = {
            'title': pr['title'],
            'files': files,
            'description': pr['description']
        }
        
        print("Analyzing code...")
        issues = await self.llm.analyze_code(diff, pr_context)
        
        if not issues:
            comment = "## AI Code Review\n\nNo issues found - code looks good!\n\n*Generated by AI Code Review Agent*"
            await self.client.add_review_comment(pr['id'], comment)
            print("✓ No issues found - added positive review")
            return
        
        inline_count = 0
        general_count = 0
        general_issues = []
        
        for issue in issues:
            issue_type = issue.get('type', 'general')
            issue_text = issue.get('issue', 'No description')
            severity = issue.get('severity', 'medium')
            
            severity_emoji = {
                'critical': '🚨',
                'high': '⚠️',
                'medium': '📝',
                'low': 'ℹ️'
            }.get(severity, '📝')
            
            if issue_type == 'inline' and 'file' in issue and 'line' in issue:
                comment = f"{severity_emoji} **{severity.upper()}**: {issue_text}"
                await self.client.add_inline_comment(
                    pr['id'],
                    issue['file'],
                    issue['line'],
                    comment
                )
                inline_count += 1
            else:
                general_issues.append(f"{severity_emoji} **{severity.upper()}**: {issue_text}")
                general_count += 1
        
        if general_issues:
            summary = "## AI Code Review Summary\n\n"
            summary += "### General Issues\n"
            for issue in general_issues:
                summary += f"- {issue}\n"
            summary += "\n*Generated by AI Code Review Agent*"
            await self.client.add_review_comment(pr['id'], summary)
        
        print(f"\n✓ Review completed:")
        print(f"  - {inline_count} inline comments added")
        print(f"  - {general_count} general issues reported")

if __name__ == "__main__":
    agent = CodeReviewAgent()
    asyncio.run(agent.run())