import asyncio
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))

from agents.pr_summarizer.config import Config, Provider
from shared.github_client import GitHubClient
from shared.gitlab_client import GitLabClient
from shared.llm_client import LLMClient
from shared.cli_args import parse_pr_args

class PRSummarizerAgent:
    def __init__(self):
        self.config = Config()
        self.llm = LLMClient(self.config.openai_api_key, model="gpt-4o")
        
        if self.config.provider == Provider.GITHUB:
            self.client = GitHubClient(
                self.config.github_token,
                self.config.repo_owner,
                self.config.repo_name
            )
        else:
            self.client = GitLabClient(
                self.config.gitlab_token,
                self.config.gitlab_url,
                self.config.repo_owner,
                self.config.repo_name
            )
    
    async def run(self):
        pr_numbers = parse_pr_args()
        
        if pr_numbers:
            print(f"Starting PR Summarizer Agent for PRs: {', '.join(map(str, pr_numbers))}")
            prs = await self.client.get_pull_requests(pr_numbers)
        else:
            print("Starting PR Summarizer Agent for recent PRs...")
            prs = await self.client.get_recent_pull_requests()
        
        if not prs:
            print("No pull requests found")
            return
        
        for pr in prs:
            await self._process_pr(pr)
    
    async def _process_pr(self, pr):
        if pr['description'] and len(pr['description']) >= 50:
            print(f"PR #{pr['id']} already has description, skipping")
            return
        
        print(f"\nGenerating summary for PR #{pr['id']}: {pr['title']}")
        
        diff = await self.client.get_diff(pr['id'])
        files = await self.client.get_changed_files(pr['id'])
        
        if not diff.strip():
            print("No diff found, skipping...")
            return
        
        print("Generating summary...")
        summary = await self.llm.summarize_pr(pr['title'], diff, files)
        
        full_summary = f"{summary}\n\n---\n*Summary generated by AI using GPT-4o*"
        
        await self.client.update_description(pr['id'], full_summary)
        print("✓ Summary generated and updated")

if __name__ == "__main__":
    agent = PRSummarizerAgent()
    asyncio.run(agent.run())