name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      create_branch:
        description: 'Create release-{tag} branch? Choose true / false'
        required: true
        type: choice
        options: [ 'true', 'false' ]

permissions:
  contents: write
  
jobs:
  create-tag-name:
    runs-on: self-hosted
    outputs:
      tag: ${{ steps.create-tag-name.outputs.tag }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create tag name
      id: create-tag-name
      run: |
        CURRENT_YEAR=$(date +%Y)
        YEAR_SINCE_START=$((CURRENT_YEAR - 2024))
        MONTH=$(date +%m)
        MONTH=$(echo $MONTH | sed 's/^0*//')
        TAG_NAME="v0.${YEAR_SINCE_START}.${MONTH}${{ github.run_number }}"
        
        echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
        echo "Generated tag name: $TAG_NAME"

  create-release-branch:
    runs-on: self-hosted
    needs: create-tag-name
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create tag
        run: |
          TAG="${{ needs.create-tag-name.outputs.tag }}"
          git tag "$TAG"
          git push origin "$TAG"
          echo "Created tag $TAG"

      - name: Create release branch
        if: ${{ github.event.inputs.create_branch == 'true' }}
        run: |
          TAG="${{ needs.create-tag-name.outputs.tag }}"
          BRANCH="release-${TAG}"
          git checkout -b "$BRANCH"
          git push origin "$BRANCH"
