name: "Handle Issue Events"

on:
  issues:
    types: [opened, closed, edited]

permissions:
  issues: write 
  contents: read
  statuses: read

jobs:
  handle-opened:
    if: github.event.action == 'opened'
    runs-on: self-hosted
    steps:
      - name: Create Jira Issue
        id: create-jira
        uses: merxxxury/jira-github-sync@v1
        with:
          jira-domain: ${{ secrets.JIRA_BASE_URL }}
          jira-email: ${{ secrets.JIRA_USER_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          action-type: 'open_issue'
          jira-project-key: 'EST'
          github-issue-title: ${{ github.event.issue.title }}
          github-issue-body: ${{ github.event.issue.body }}
          github-issue-url: ${{ github.event.issue.html_url }}
          jira-issue-type: 'Bug'
      
      - name: Add JIRA issue id to Github issue as label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.payload.issue.number;

            const labelToAdd = "${{ steps.create-jira.outputs.jira-issue-key }}";

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              labels: [labelToAdd]
            });

            console.log(`Label "${labelToAdd}" added to issue #${issue_number}`);

  handle-edited:
    if: github.event.action == 'edited'
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Extract Jira Key for edit issue
        id: extract-jira-key
        uses: ./.github/actions/extract-jira-key
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          ACTION_TYPE: "edit_issue"
          JIRA_ISSUE_KEY: ${{ steps.extract-jira-key.outputs.jira_key }}
          GITHUB_ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_ISSUE_URL: ${{ github.event.issue.html_url }}

        run: python .github/scripts/edit_issue.py
          

  handle-closed:
    if: github.event.action == 'closed'
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Extract Jira Key for close issue
        id: extract-jira-key
        uses: ./.github/actions/extract-jira-key
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Jira Issue\
        if: steps.extract-jira-key.outputs.jira_key != ''
        uses: merxxxury/jira-github-sync@v1
        with:
          jira-domain: ${{ secrets.JIRA_BASE_URL }}
          jira-email: ${{ secrets.JIRA_USER_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          action-type: 'close_issue'
          jira-issue-key: ${{ steps.extract-jira-key.outputs.jira_key }}
          jira-closed-status-name: 'ready for test'